version: "3.8"

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${HTTP_ON_HOST}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
      - redis
  php:
    build:
      args:
        PUID: ${PUID}
        PGID: ${PGID}
      context: ./
      dockerfile: DockerFile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_ON_HOST}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_ON_HOST}:6379
  worker:
    build:
      context: ./
      dockerfile: ./DockerFile
    volumes:
      - ./src:/var/www/laravel
    command: ["php", "artisan", "queue:work", "--queue=emails"]
  scheduler:
    build:
      context: ./
      dockerfile: ./DockerFile
    volumes:
      - ./src:/var/www/laravel
    command: ["php", "artisan", "schedule:work"]

volumes:
  db_data: